- .github/CONTRIBUTING.md
Added Contributing file based on Atom project
Closes #1 
Contributing file is the first place to find "how is possible to help the project".
> #1 Add Contributing file

- introduction_to_conan.rst
> Added a line so the bullet would appear

- continuous_integration.rst
- continuous_integration/bincrafters_package_tools.rst
- continuous_integration/introduction_to_ci.rst
- index.rst
Hi!
I just added Bincrafters package tools on our docs
Fixes #69
Regards!
> Add Bincrafters package tools (#69)

- contributing_to_packages/package_guidelines_required.rst
Examples provided had indentation problems.
> Fix code example indentation

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/inclusion_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/upstream_update.md
Updates issue templates
Closes #531
Making the issue templates more helpful and more specific for different cases
> Update issue templates

- using_packages.rst
> Fix link to conan installation instructions

- howtos/add_fpic_option_to_recipe.rst
> Use map for default options instead of tuple

- recipes/sdl2/all/conanfile.py
> migrate pusleaudio to CCI

- recipes/portaudio/all/CMakeLists.txt
- recipes/portaudio/all/FindPortaudio.cmake
- recipes/portaudio/all/conandata.yml
- recipes/portaudio/all/conanfile.py
- recipes/portaudio/all/patches/a1f61a9a2cb74d11cfe743d72763850aa246a092.diff
- recipes/portaudio/all/patches/ea11061b20f637f8f707a4a225d37ff58ab54dc0.diff
- recipes/portaudio/all/test_package/CMakeLists.txt
- recipes/portaudio/all/test_package/conanfile.py
- recipes/portaudio/all/test_package/test_package.c
- recipes/portaudio/config.yml
Ported from https://github.com/bincrafters/conan-portaudio
+ smallish update to CMake wrapper
_____
Same here, let's ignore GCC 9 / Clang 9 errors for the moment
> add portaudio/v190600.20161030

- recipes/sdl2/all/conandata.yml
- recipes/sdl2/config.yml
Fixes https://github.com/bincrafters/community/issues/1330
> add sdl2/2.0.14

- recipes/ffmpeg/all/conanfile.py
> ffmpeg: bump openjpeg

- recipes/imgui-sfml/all/CMakeLists.txt
- recipes/imgui-sfml/all/conandata.yml
- recipes/imgui-sfml/all/conanfile.py
- recipes/imgui-sfml/all/patches/0001-conan-libs.patch
- recipes/imgui-sfml/all/test_package/CMakeLists.txt
- recipes/imgui-sfml/all/test_package/conanfile.py
- recipes/imgui-sfml/all/test_package/test_package.cpp
- recipes/imgui-sfml/config.yml
Ported from https://github.com/bincrafters/conan-imgui-sfml
Plus adding an option to the `conanfile.py` and the structure to `conandata.yml` which allows to configure the imgui version. Fixes #1349 
Also we have a recipe for this now for a long time, so this closes #1125
> add imgui-sfml/2.1

- recipes/gst-plugins-base/all/conandata.yml
- recipes/gst-plugins-base/all/conanfile.py
- recipes/gst-plugins-base/all/patches/0001-meson-Don-t-try-to-find-gio-unix-on-Windows.patch
- recipes/gst-plugins-base/all/test_package/CMakeLists.txt
- recipes/gst-plugins-base/all/test_package/conanfile.py
- recipes/gst-plugins-base/all/test_package/test_package.cpp
- recipes/gst-plugins-base/config.yml
direct port of https://github.com/bincrafters/conan-gst-plugins-base
> gst-plugins-base

- recipes/sdl2/all/conanfile.py
More robust version comparison.
Might break in the future without this small fix.
> [sdl2] Compare versions with tools.Version

- recipes/sdl2/all/conanfile.py
fixes bincrafters/community#1373
> add libunwind dependency

- recipes/sdl2/all/conanfile.py
Dummy update to trigger CI + upload
> sdl2: simplify source()

- .github/workflows/conan.yml
- azure-pipelines.yml
- recipes/pcapplusplus/all/conandata.yml
- recipes/pcapplusplus/all/conanfile.py
- recipes/pcapplusplus/all/test_package/CMakeLists.txt
- recipes/pcapplusplus/all/test_package/conanfile.py
- recipes/pcapplusplus/all/test_package/test_package.cpp
- recipes/pcapplusplus/config.yml
Migrated from https://github.com/bincrafters/conan-pcapplusplus
and some small CI changes as the counterpart for https://github.com/bincrafters/bincrafters-package-tools/pull/33, more changes like this are coming
> add pcapplusplus/20.08

- recipes/sdl2_ttf/all/conanfile.py
the recipe currently available on bincrafters remote is this one: https://github.com/bincrafters/conan-sdl2_ttf/blob/stable/2.0.15/conanfile.py
> regenerate sdl2_ttf

- recipes/wxwidgets/all/conandata.yml
- recipes/wxwidgets/all/conanfile.py
- recipes/wxwidgets/config.yml
fixes bincrafters/community#1397
> wxwidgets: 3.1.5

- recipes/ffmpeg/config.yml
now that conan-io/conan-center-index#6707 is merged
> disable ffmpeg

- .github/workflows/conan.yml
- azure-pipelines.yml
- recipes/ruby_installer/2.x.x/conanfile.py
Pretty much only to test BPT / CI.
> Update CI + ruby_installer: add required_conan_version and update OpenSSL

- .github/workflows/conan.yml
- azure-pipelines.yml
- recipes/sdl2_mixer/2.0.4/conanfile.py
Also using such small changes once more to test further CI changes
> sdl2_mixer: Update SDL to 2.0.16

- recipes/wxwidgets/3.1.3/conanfile.py
> Add armhf and arm64 arch_suffix to wxWidgets conanfile.py

- recipes/fluidsynth/all/conanfile.py
- recipes/fluidsynth/all/test_package/conanfile.py
See https://github.com/conan-io/docs/commit/2371992fdf71857de7bfc3c3e7873b0d69f9768c
> fluidsynth: hotfix for renamed parameter + update deps

- .github/workflows/auto-merge.yml
- .github/workflows/conan.yml
- .github/workflows/docs.yml
> CI updates
